return {
    InputDeviceType = {
        Keyboard = "Keyboard",
        Console = "Console",
        Mobile = "Mobile",
        VR = "VR"
    },

    SettingType = {
        Boolean = "Boolean",
        Slider = "Slider",
        Keybind = "Keybind"
    },

    AxisEmotion = {
        Game = "Game",
        Happy = "Happy",
        Nervous = "Nervous",
        Neutral = "Neutral",
        Sad = "Sad",
        Shocked = "Shocked",
        VeryHappy = "VeryHappy",
        Wink = "Wink"
    }
}