local playerGui = game.Players.LocalPlayer.PlayerGui.Gui

return {
	Other = {
		TechDemo = {
			Name = "Tech Demo",
			Id = 77387141340458,
			ReturnTo = playerGui.Extras.Extras.Extras
		}
	},
	
	OlderVersions = {
		{
			Name = "ALPHA 0.4a (11/01/26)",
			Id = 71595099514821,
			ReturnTo = playerGui.Extras.Extras.OlderVersions
		},
		{
			Name = "ALPHA 0.3a (24/02/25)",
			Id = 131286397482643,
			ReturnTo = playerGui.Extras.Extras.OlderVersions
		},
		{
			Name = "ALPHA 0.2a (28/10/24)",
			Id = 113470732219082,
			ReturnTo = playerGui.Extras.Extras.OlderVersions
		},
		{
			Name = "ALHPA 0.1a (04/09/24)",
			Id = 83504475838006,
			ReturnTo = playerGui.Extras.Extras.OlderVersions
		}
	}
}