return {
    Music = {
        ["0"] = {
            NormalId = "rbxassetid://123938165905007"
        },
        ["ImpassChapter3Remix"] = {
            DisplayName = "Impass (Chapter 3 Remix)",
            NormalId = "rbxassetid://123938165905007"
        },
        ["SmallLengthExperiment"] = {
            DisplayName = "Small-Length Experiment",
            NormalId = "rbxassetid://123938165905007"
        },
        ["TunnelerButItSucks"] = {
            DisplayName = "TUNNELER But it sucks",
            NormalId = "rbxassetid://123938165905007"
        },
        ["hurricane_ambience"] = {
            NormalId = "rbxassetid://123938165905007"
        },
    },

    SoundEffects = {
        PlaceHolder = {
            SoundId = "rbxassetid://123938165905007"
        },
        GunFire = {
            SoundId = "rbxassetid://1905367471", -- this is a public sound so it does not have to be updated
            VolumeMultiplier = 0.1
        }
    }
}