return {
    Announcer = {
        wtl0 = {
            Subtitle = "Welcome to level 0.",
			SoundId = "rbxassetid://123938165905007"
        },
        wtl1 = {
            Subtitle = "Welcome to the level 1.",
			SoundId = "rbxassetid://123938165905007"
        },
        wtl2 = {
            Subtitle = "Welcome level 2.",
			SoundId = "rbxassetid://123938165905007"
        },
        wtl3 = {
            Subtitle = "Welcome level to 3.",
			SoundId = "rbxassetid://123938165905007"
        },
        wtl4 = {
            Subtitle = "4. Level 4. Welcome to level. ",
			SoundId = "rbxassetid://123938165905007"
        },
        wtl5 = {
            Subtitle = "Welcome to level 5.",
			SoundId = "rbxassetid://123938165905007"
        },
        wtl6 = {
            Subtitle = "Welcome to level 6.",
			SoundId = "rbxassetid://123938165905007"
        },
        wtl7 = {
            Subtitle = "7",
			SoundId = "rbxassetid://123938165905007"
        },
        wtl8 = {
            Subtitle = ".8 level ot emocloW",
			SoundId = "rbxassetid://123938165905007"
        },
        wtl9 = {
            Subtitle = "Welcome to 9.",
			SoundId = "rbxassetid://123938165905007"
        }
    },



    Axis = {
        Confuzzled = {
			Subtitle = "Uhhhhhhhhhhhhh...",
			Emotion = "Happy",
			SoundId = "rbxassetid://123938165905007"
		},
		BeCarefull = {
			Subtitle = "Be carefulness!",
			Emotion = "Shocked",
			SoundId = "rbxassetid://123938165905007"
		},
		Carefull = {
			Subtitle = "Carful!",
			Emotion = "Shocked",
			SoundId = "rbxassetid://123938165905007"
		},
		LookOut = {
			Subtitle = "Watch out!",
			Emotion = "Shocked",
			SoundId = "rbxassetid://123938165905007"
		},
		BackUp = {
			Subtitle = "Back up!",
			Emotion = "Shocked",
			SoundId = "rbxassetid://123938165905007"
		},
		OhNo = {
			Subtitle = "Oh no!",
			Emotion = "Shocked",
			SoundId = "rbxassetid://123938165905007"
		},
		GoodMorning = {
			Subtitle = "Good morning! A new day, a new experiment",
			Emotion = "Happy",
			SoundId = "rbxassetid://123938165905007"
		},
		WelcomeBack = {
			Subtitle = "Welcome back. I hope that you a sleep. Continue experiment?",
			Emotion = "Happy",
			SoundId = "rbxassetid://123938165905007"
		},
		StretchWell = {
			Subtitle = "Hello! make sure you stretch before you stretch",
			Emotion = "Happy",
			SoundId = "rbxassetid://123938165905007"
		},
		WellRested = {
			Subtitle = "I happy you be sleep! If you more sleep, then the more experement!",
			Emotion = "Happy",
			SoundId = "rbxassetid://123938165905007"
		},
		ImAxis = {
			Subtitle = "Hi. I'm axis. I'm your personal experimenting friend.",
			Emotion = "Wink",
			SoundId = "rbxassetid://123938165905007"
		},
		IWatchU = {
			Subtitle = "I'm here to look at you though the experement, so you will be recorded to be looked at further.",
			Emotion = "Happy",
			SoundId = "rbxassetid://123938165905007"
		},
		TestingIsDangerous = {
			Subtitle = "It's important to have the knowlage that the VERY DANGEROUS.",
			Emotion = "Neutral",
			SoundId = "rbxassetid://123938165905007"
		},
		TheTestingWillBegin = {
			Subtitle = "Ok, time for the experiment thingy.",
			Emotion = "Happy",
			SoundId = "rbxassetid://123938165905007"
		},
		TunnelsConfuzzled = {
			Subtitle = "As you can see, Teleportation-Holes are very confusing.",
			Emotion = "Happy",
			SoundId = "rbxassetid://123938165905007"
		},
		Level0 = {
			Subtitle = "This is level 0. Please now do the level 0.",
			Emotion = "Happy",
			SoundId = "rbxassetid://123938165905007"
		},
		Level0Yay = {
			Subtitle = "Yes! Did!!!!!",
			Emotion = "VeryHappy",
			SoundId = "rbxassetid://123938165905007"
		},
		RestAreas = {
			Subtitle = "The experement can be VERY much tiredness. Here is a place where you can un-tired yourself!",
			Emotion = "Happy",
			SoundId = "rbxassetid://123938165905007"
		},
		AnotherTestDone = {
			Subtitle = "You did another test now, and you WILL like the stuff we have for you afterwards. ",
			Emotion = "Happy",
			SoundId = "rbxassetid://123938165905007	"
		},
		EclipseHoleMakingDevice = {
			Subtitle = "This is the Eclipse Corporation Small-Length Teleportation-Hole Making Device! Please now go get the Eclipse Corporation Small-Length Teleportation-Hole Making Device",
			Emotion = "Happy",
			SoundId = "rbxassetid://123938165905007"
		},
		DeviceSafety = {
			Subtitle = "You may find the Eclipse Corporation Small-Length Teleportation-Hole Making Device to be scary, but it is safe, as long as you are safely.",
			Emotion = "Happy",
			SoundId = "rbxassetid://123938165905007"
		},
		SafetyGuildlines = {
			Subtitle = "You now have the Eclipse Corporation Small-Length Teleportation-Hole Making Device! Now, I will tell you the rules so you are safely",
			Emotion = "Happy",
			SoundId = "rbxassetid://123938165905007"
		},
		Rule1 = {
			Subtitle = "Rule 1. Teleportation-Holes will not on metalic surfaces.",
			Emotion = "Happy",
			SoundId = "rbxassetid://123938165905007"
		},
		Rule2 = {
			Subtitle = "Rule 2. If you fall, the thingies on your legs will make sure you're safely.",
			Emotion = "Happy",
			SoundId = "rbxassetid://123938165905007"
		},
		Rule3 = {
			Subtitle = "Rule 3. The Eclipse Corporation Small-Length Teleportation-Hole Making Device does NOT like your bones if your arms are straight.",
			Emotion = "Neutral",
			SoundId = "rbxassetid://123938165905007"
		},
		Rule4 = {
			Subtitle = "Rule 4. Do not touch the gun, unless you are touching the gun.",
			Emotion = "Neutral",
			SoundId = "rbxassetid://123938165905007"
		},
		Rule5 = {
			Subtitle = "Rule 5. Don't compare the Eclipse Corporation Small-Length Teleportation-Hole Making Device to the Ecliptic Industries Short-Distance Tunneling Device.",
			Emotion = "Neutral",
			SoundId = "rbxassetid://123938165905007"
		},
		Rule6 = {
			Subtitle = "Rule 6. The rules are the rules. Do not not the rules.",
			Emotion = "Happy",
			SoundId = "rbxassetid://123938165905007"
		},
		Rule7 = {
			Subtitle = "Rule 7. Do not water the device. It will make the device sad.",
			Emotion = "Neutral",
			SoundId = "rbxassetid://123938165905007"
		},
		Rule8 = {
			Subtitle = "Rule 8. Don't shoot people. We don't know exactaly what happens, but it's probably not a good thing.",
			Emotion = "Neutral",
			SoundId = "rbxassetid://123938165905007"
		},
		Rule9 = {
			Subtitle = "Rule 9. Don't the device if you don't want to the device",
			Emotion = "Neutral",
			SoundId = "rbxassetid://123938165905007"
		},
		Rule10 = {
			Subtitle = "Rule 10. Don't think about how the Eclipse Corporation Small-Length Teleportation-Hole Making Device works. ",
			Emotion = "Neutral",
			SoundId = "rbxassetid://123938165905007"
		},
		Rule10Extra = {
			Subtitle = "Test subjects that have thought about it have been found to have a higher chance of getting diagnosed with a very minor case of serious brain damage.",
			Emotion = "Neutral",
			SoundId = "rbxassetid://123938165905007"
		},
		Rule11Wait = {
			Subtitle = "Rule 11. Wait.....................................................................",
			Emotion = "Happy",
			SoundId = "rbxassetid://123938165905007"
		},
		Sorry = {
			Subtitle = "Sorry, just give me a unit of time.",
			Emotion = "Neutral",
			SoundId = "rbxassetid://123938165905007"
		},
		Rule11 = {
			Subtitle = "Rule 11. Have enjoyment!",
			Emotion = "Wink",
			SoundId = "rbxassetid://123938165905007"
		},
		SpeedyThingGoesInSpeedyThingComesOut = {
			Subtitle = "New level. Don't be scared by the room is very big. You will have the same speed while travaling through teleportation-holes. For example: [Pre-recorded sounding voice] Speedy thing goes in, Speedy thing comes out.",
			Emotion = "Happy",
			SoundId = "rbxassetid://123938165905007"
		},
		SpeedyThingGoesInSpeedyThingComesOut2 = {
			Subtitle = "The same Teleportatoin-Hole speed thing also applies to other objects.",
			Emotion = "Happy",
			SoundId = "rbxassetid://123938165905007"
		},
		urgoodatthis = {
			Subtitle = "You really be flying through the chambers. I should tell them to make it less fly-throughable",
			Emotion = "Happy",
			SoundId = "rbxassetid://123938165905007"
		},
		FlamingLikeNote = {
			Subtitle = "You completed this chamber all on your own. This shows that you have at least 7 brain cells.",
			Emotion = "Happy",
			SoundId = "rbxassetid://123938165905007"
		},
		NoTouchy = {
			Subtitle = "Do not touch the power bullets. It WILL make you become die.",
			Emotion = "Neutral",
			SoundId = "rbxassetid://123938165905007"
		},
		SafeyGuidlineTimeStupid = {
			Subtitle = "Safe rule time...... so stupid.",
			Emotion = "Happy",
			SoundId = "rbxassetid://123938165905007"
		},
		UrSpeed = {
			Subtitle = "[INSERT COMPLIMENT]",
			Emotion = "Happy",
			SoundId = "rbxassetid://123938165905007"
		},
		DualHoleMakingDevice = {
			Subtitle = "If you want to do more experementing, please get the upgraded Eclipse Corporation Small-Length Teleportation-Hole Making Device to be able to continue the experement.",
			Emotion = "Game",
			SoundId = "rbxassetid://123938165905007"
		},
		ItMakesBothHoles = {
			Subtitle = "Congratulates! You now have the upgraded Eclipse Corporation Small-Length Teleportation-Hole Making Device! Now you can place both Teleportation-Holes.",
			Emotion = "Happy",
			SoundId = "rbxassetid://123938165905007"
		},
		SafteyGuidlineTime = {
			Subtitle = "Still remember, that you need to be safely. If your line is on your life, then it safe rule time!",
			Emotion = "Happy",
			SoundId = "rbxassetid://123938165905007"
		},
		NotOfficial = {
			Subtitle = "Yes that is a totaly real motto I totaly didn't make up on the spot.",
			Emotion = "Nervous",
			SoundId = "rbxassetid://123938165905007"
		},
		DontLeavePls = {
			Subtitle = "Don't leave the experementing place again. It is not safely.",
			Emotion = "Sad",
			SoundId = "rbxassetid://123938165905007"
		},
		PostTestingInterview = {
			Subtitle = "I would like to hear you thinking on the experement. Will you want to do the after experement interview?",
			Emotion = "Happy",
			SoundId = "rbxassetid://123938165905007"
		},
		InterestingFact = {
			Subtitle = "Here's an interesting fact: Running was invented in 1748 by Thomas Running when he tried to walk twice at the same time.",
			Emotion = "Happy",
			SoundId = "rbxassetid://123938165905007"
		},
		BestTestSubject = {
			Subtitle = "Ur the only test subject I know so far, but you sure are a yes.",
			Emotion = "Happy",
			SoundId = "rbxassetid://123938165905007"
		},
		NeedExplainNextTest = {
			Subtitle = "Before you go to the next level, I am need to say that it has the VERY DANGEROUS.",
			Emotion = "Neutral",
			SoundId = "rbxassetid://123938165905007"
		},
		NextTestDanger = {
			Subtitle = "I can't able to come with you also, so you will be yourself.",
			Emotion = "Sad",
			SoundId = "rbxassetid://123938165905007"
		},
		GudLuck = {
			Subtitle = "I really hope to see you after the experement, goodest of luck.",
			Emotion = "Sad",
			SoundId = "rbxassetid://123938165905007"
		},
		WatchOutFor = {
			Subtitle = "Wait.... watch out for the--",
			Emotion = "Shocked",
			SoundId = "rbxassetid://123938165905007"
		},
		UrOk = {
			Subtitle = "You aren't became die! There be medical equitment and stuff if you are ow.",
			Emotion = "Sad",
			SoundId = "rbxassetid://123938165905007"
		},
		LetsContinue = {
			Subtitle = "Oh ok, continue experement.",
			Emotion = "Neutral",
			SoundId = "rbxassetid://123938165905007"
		},
		TwoMore = {
			Subtitle = "there are 2 more rooms. They have very much difficulty, but you can complete the!",
			Emotion = "Neutral",
			SoundId = "rbxassetid://123938165905007"
		},
		OneMore = {
			Subtitle = "Nice, one more room untill the completion!",
			Emotion = "Neutral",
			SoundId = "rbxassetid://123938165905007"
		},
		PowerMaintenace = {
			Subtitle = "Maybe there be the electric maintenance today...",
			Emotion = "Neutral",
			SoundId = "rbxassetid://123938165905007"
		},
		WeWait = {
			Subtitle = "I guess we wait.",
			Emotion = "Neutral",
			SoundId = "rbxassetid://123938165905007"
		},
		ThisNotPartOfTheTest = {
			Subtitle = "WWWWHHHHAAATTTTT IIIIISSSSS HHHAPPIINNG!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! GRAB ON TO SOMETHING!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
			Emotion = "Shocked",
			SoundId = "rbxassetid://123938165905007"
		},
		whatdoido = {
			Subtitle = "WHATDOIDOWHATDOIDOWHATWDOWIHJWEIJWDIUASHDUIBDOLIWUEGBFOLPIEWUBGFL",
			Emotion = "Shocked",
			SoundId = "rbxassetid://123938165905007"
		}
    }
}