return {
    Music = {
        ["0"] = {
            NormalId = "rbxassetid://90465990150232"
        },
        ["ImpassChapter3Remix"] = {
            DisplayName = "Impass (Chapter 3 Remix)",
            NormalId = "rbxassetid://123889965018687"
        },
        ["SmallLengthExperiment"] = {
            DisplayName = "Small-Length Experiment",
            NormalId = "rbxassetid://103364891349469"
        },
        ["TunnelerButItSucks"] = {
            DisplayName = "TUNNELER But it sucks",
            NormalId = "rbxassetid://98124873505226"
        },
        ["hurricane_ambience"] = {
            NormalId = "rbxassetid://85150335135549"
        },
    },

    SoundEffects = {
        PlaceHolder = {
            Id = "rbxassetid://78561653916914"
        },
        GunFire = {
            Id = "rbxassetid://1905367471",
            VolumeMultiplier = 0.1
        }
    }
}