return {
    Announcer = {
        wtl0 = {
            Subtitle = "Welcome to level 0.",
			SoundId = "rbxassetid://82267025125991"
        },
        wtl1 = {
            Subtitle = "Welcome to the level 1.",
			SoundId = "rbxassetid://128678424923500"
        },
        wtl2 = {
            Subtitle = "Welcome level 2.",
			SoundId = "rbxassetid://97668775746699"
        },
        wtl3 = {
            Subtitle = "Welcome level to 3.",
			SoundId = "rbxassetid://90853945788803"
        },
        wtl4 = {
            Subtitle = "4. Level 4. Welcome to level. ",
			SoundId = "rbxassetid://128272391150530"
        },
        wtl5 = {
            Subtitle = "Welcome to level 5.",
			SoundId = "rbxassetid://94427408652499"
        },
        wtl6 = {
            Subtitle = "Welcome to level 6.",
			SoundId = "rbxassetid://132013043854463"
        },
        wtl7 = {
            Subtitle = "7",
			SoundId = "rbxassetid://86679589670601"
        },
        wtl8 = {
            Subtitle = ".8 level ot emocloW",
			SoundId = "rbxassetid://79810803814951"
        },
        wtl9 = {
            Subtitle = "Welcome to 9.",
			SoundId = "rbxassetid://82107490169139"
        }
    },



    Axis = {
        Confuzzled = {
			Subtitle = "Uhhhhhhhhhhhhh...",
			Emotion = "Happy",
			SoundId = "rbxassetid://98021560141356"
		},
		BeCarefull = {
			Subtitle = "Be carefulness!",
			Emotion = "Shocked",
			SoundId = "rbxassetid://93135722480914"
		},
		Carefull = {
			Subtitle = "Carful!",
			Emotion = "Shocked",
			SoundId = "rbxassetid://78603509494998"
		},
		LookOut = {
			Subtitle = "Watch out!",
			Emotion = "Shocked",
			SoundId = "rbxassetid://83879898844564"
		},
		BackUp = {
			Subtitle = "Back up!",
			Emotion = "Shocked",
			SoundId = "rbxassetid://77652667996677"
		},
		OhNo = {
			Subtitle = "Oh no!",
			Emotion = "Shocked",
			SoundId = "rbxassetid://120218968860476"
		},
		GoodMorning = {
			Subtitle = "Good morning! A new day, a new experiment",
			Emotion = "Happy",
			SoundId = "rbxassetid://108917757496688"
		},
		WelcomeBack = {
			Subtitle = "Welcome back. I hope that you a sleep. Continue experiment?",
			Emotion = "Happy",
			SoundId = "rbxassetid://119280719559597"
		},
		StretchWell = {
			Subtitle = "Hello! make sure you stretch before you stretch",
			Emotion = "Happy",
			SoundId = "rbxassetid://76495454102565"
		},
		WellRested = {
			Subtitle = "I happy you be sleep! If you more sleep, then the more experement!",
			Emotion = "Happy",
			SoundId = "rbxassetid://75999034578055"
		},
		ImAxis = {
			Subtitle = "Hi. I'm axis. I'm your personal experimenting friend.",
			Emotion = "Wink",
			SoundId = "rbxassetid://105431599926566"
		},
		IWatchU = {
			Subtitle = "I'm here to look at you though the experement, so you will be recorded to be looked at further.",
			Emotion = "Happy",
			SoundId = "rbxassetid://113813006020294"
		},
		TestingIsDangerous = {
			Subtitle = "It's important to have the knowlage that the VERY DANGEROUS.",
			Emotion = "Neutral",
			SoundId = "rbxassetid://122336422168561"
		},
		TheTestingWillBegin = {
			Subtitle = "Ok, time for the experiment thingy.",
			Emotion = "Happy",
			SoundId = "rbxassetid://129984738649956"
		},
		TunnelsConfuzzled = {
			Subtitle = "As you can see, Teleportation-Holes are very confusing.",
			Emotion = "Happy",
			SoundId = "rbxassetid://71643595509502"
		},
		Level0 = {
			Subtitle = "This is level 0. Please now do the level 0.",
			Emotion = "Happy",
			SoundId = "rbxassetid://127203990880407"
		},
		Level0Yay = {
			Subtitle = "Yes! Did!!!!!",
			Emotion = "VeryHappy",
			SoundId = "rbxassetid://85778912883205"
		},
		RestAreas = {
			Subtitle = "The experement can be VERY much tiredness. Here is a place where you can un-tired yourself!",
			Emotion = "Happy",
			SoundId = "rbxassetid://97616424342443"
		},
		AnotherTestDone = {
			Subtitle = "You did another test now, and you WILL like the stuff we have for you afterwards. ",
			Emotion = "Happy",
			SoundId = "rbxassetid://120325138231538	"
		},
		EclipseHoleMakingDevice = {
			Subtitle = "This is the Eclipse Corporation Small-Length Teleportation-Hole Making Device! Please now go get the Eclipse Corporation Small-Length Teleportation-Hole Making Device",
			Emotion = "Happy",
			SoundId = "rbxassetid://132702863825119"
		},
		DeviceSafety = {
			Subtitle = "You may find the Eclipse Corporation Small-Length Teleportation-Hole Making Device to be scary, but it is safe, as long as you are safely.",
			Emotion = "Happy",
			SoundId = "rbxassetid://77163370414433"
		},
		SafetyGuildlines = {
			Subtitle = "You now have the Eclipse Corporation Small-Length Teleportation-Hole Making Device! Now, I will tell you the rules so you are safely",
			Emotion = "Happy",
			SoundId = "rbxassetid://133887879193006"
		},
		Rule1 = {
			Subtitle = "Rule 1. Teleportation-Holes will not on metalic surfaces.",
			Emotion = "Happy",
			SoundId = "rbxassetid://129745746029297"
		},
		Rule2 = {
			Subtitle = "Rule 2. If you fall, the thingies on your legs will make sure you're safely.",
			Emotion = "Happy",
			SoundId = "rbxassetid://94587199675042"
		},
		Rule3 = {
			Subtitle = "Rule 3. The Eclipse Corporation Small-Length Teleportation-Hole Making Device does NOT like your bones if your arms are straight.",
			Emotion = "Neutral",
			SoundId = "rbxassetid://118359909290231"
		},
		Rule4 = {
			Subtitle = "Rule 4. Do not touch the gun, unless you are touching the gun.",
			Emotion = "Neutral",
			SoundId = "rbxassetid://83600626728909"
		},
		Rule5 = {
			Subtitle = "Rule 5. Don't compare the Eclipse Corporation Small-Length Teleportation-Hole Making Device to the Ecliptic Industries Short-Distance Tunneling Device.",
			Emotion = "Neutral",
			SoundId = "rbxassetid://108986046153701"
		},
		Rule6 = {
			Subtitle = "Rule 6. The rules are the rules. Do not not the rules.",
			Emotion = "Happy",
			SoundId = "rbxassetid://117113447446145"
		},
		Rule7 = {
			Subtitle = "Rule 7. Do not water the device. It will make the device sad.",
			Emotion = "Neutral",
			SoundId = "rbxassetid://132497536314611"
		},
		Rule8 = {
			Subtitle = "Rule 8. Don't shoot people. We don't know exactaly what happens, but it's probably not a good thing.",
			Emotion = "Neutral",
			SoundId = "rbxassetid://98235256940467"
		},
		Rule9 = {
			Subtitle = "Rule 9. Don't the device if you don't want to the device",
			Emotion = "Neutral",
			SoundId = "rbxassetid://96830146383978"
		},
		Rule10 = {
			Subtitle = "Rule 10. Don't think about how the Eclipse Corporation Small-Length Teleportation-Hole Making Device works. ",
			Emotion = "Neutral",
			SoundId = "rbxassetid://78386566482736"
		},
		Rule10Extra = {
			Subtitle = "Test subjects that have thought about it have been found to have a higher chance of getting diagnosed with a very minor case of serious brain damage.",
			Emotion = "Neutral",
			SoundId = "rbxassetid://107040525657379"
		},
		Rule11Wait = {
			Subtitle = "Rule 11. Wait.....................................................................",
			Emotion = "Happy",
			SoundId = "rbxassetid://139809461666309"
		},
		Sorry = {
			Subtitle = "Sorry, just give me a unit of time.",
			Emotion = "Neutral",
			SoundId = "rbxassetid://74468407773850"
		},
		Rule11 = {
			Subtitle = "Rule 11. Have enjoyment!",
			Emotion = "Wink",
			SoundId = "rbxassetid://94041788795070"
		},
		SpeedyThingGoesInSpeedyThingComesOut = {
			Subtitle = "New level. Don't be scared by the room is very big. You will have the same speed while travaling through teleportation-holes. For example: [Pre-recorded sounding voice] Speedy thing goes in, Speedy thing comes out.",
			Emotion = "Happy",
			SoundId = "rbxassetid://111735673863477"
		},
		SpeedyThingGoesInSpeedyThingComesOut2 = {
			Subtitle = "The same Teleportatoin-Hole speed thing also applies to other objects.",
			Emotion = "Happy",
			SoundId = "rbxassetid://105143688841669"
		},
		urgoodatthis = {
			Subtitle = "You really be flying through the chambers. I should tell them to make it less fly-throughable",
			Emotion = "Happy",
			SoundId = "rbxassetid://95854126611359"
		},
		FlamingLikeNote = {
			Subtitle = "You completed this chamber all on your own. This shows that you have at least 7 brain cells.",
			Emotion = "Happy",
			SoundId = "rbxassetid://140360066465189"
		},
		NoTouchy = {
			Subtitle = "Do not touch the power bullets. It WILL make you become die.",
			Emotion = "Neutral",
			SoundId = "rbxassetid://80092784823575"
		},
		SafeyGuidlineTimeStupid = {
			Subtitle = "Safe rule time...... so stupid.",
			Emotion = "Happy",
			SoundId = "rbxassetid://74656196898381"
		},
		UrSpeed = {
			Subtitle = "[INSERT COMPLIMENT]",
			Emotion = "Happy",
			SoundId = "rbxassetid://87805896813072"
		},
		DualHoleMakingDevice = {
			Subtitle = "If you want to do more experementing, please get the upgraded Eclipse Corporation Small-Length Teleportation-Hole Making Device to be able to continue the experement.",
			Emotion = "Game",
			SoundId = "rbxassetid://106316945707057"
		},
		ItMakesBothHoles = {
			Subtitle = "Congratulates! You now have the upgraded Eclipse Corporation Small-Length Teleportation-Hole Making Device! Now you can place both Teleportation-Holes.",
			Emotion = "Happy",
			SoundId = "rbxassetid://120376429062146"
		},
		SafteyGuidlineTime = {
			Subtitle = "Still remember, that you need to be safely. If your line is on your life, then it safe rule time!",
			Emotion = "Happy",
			SoundId = "rbxassetid://93133926600767"
		},
		NotOfficial = {
			Subtitle = "Yes that is a totaly real motto I totaly didn't make up on the spot.",
			Emotion = "Nervous",
			SoundId = "rbxassetid://122719621188851"
		},
		DontLeavePls = {
			Subtitle = "Don't leave the experementing place again. It is not safely.",
			Emotion = "Sad",
			SoundId = "rbxassetid://90116978084510"
		},
		PostTestingInterview = {
			Subtitle = "I would like to hear you thinking on the experement. Will you want to do the after experement interview?",
			Emotion = "Happy",
			SoundId = "rbxassetid://121444321568369"
		},
		InterestingFact = {
			Subtitle = "Here's an interesting fact: Running was invented in 1748 by Thomas Running when he tried to walk twice at the same time.",
			Emotion = "Happy",
			SoundId = "rbxassetid://84562355424168"
		},
		BestTestSubject = {
			Subtitle = "Ur the only test subject I know so far, but you sure are a yes.",
			Emotion = "Happy",
			SoundId = "rbxassetid://78236595804696"
		},
		NeedExplainNextTest = {
			Subtitle = "Before you go to the next level, I am need to say that it has the VERY DANGEROUS.",
			Emotion = "Neutral",
			SoundId = "rbxassetid://137298627344549"
		},
		NextTestDanger = {
			Subtitle = "I can't able to come with you also, so you will be yourself.",
			Emotion = "Sad",
			SoundId = "rbxassetid://94464948275265"
		},
		GudLuck = {
			Subtitle = "I really hope to see you after the experement, goodest of luck.",
			Emotion = "Sad",
			SoundId = "rbxassetid://111281266893418"
		},
		WatchOutFor = {
			Subtitle = "Wait.... watch out for the--",
			Emotion = "Shocked",
			SoundId = "rbxassetid://88996683396548"
		},
		UrOk = {
			Subtitle = "You aren't became die! There be medical equitment and stuff if you are ow.",
			Emotion = "Sad",
			SoundId = "rbxassetid://136195211341053"
		},
		LetsContinue = {
			Subtitle = "Oh ok, continue experement.",
			Emotion = "Neutral",
			SoundId = "rbxassetid://81689846228438"
		},
		TwoMore = {
			Subtitle = "there are 2 more rooms. They have very much difficulty, but you can complete the!",
			Emotion = "Neutral",
			SoundId = "rbxassetid://80813120062462"
		},
		OneMore = {
			Subtitle = "Nice, one more room untill the completion!",
			Emotion = "Neutral",
			SoundId = "rbxassetid://138966588322596"
		},
		PowerMaintenace = {
			Subtitle = "Maybe there be the electric maintenance today...",
			Emotion = "Neutral",
			SoundId = "rbxassetid://111567213725336"
		},
		WeWait = {
			Subtitle = "I guess we wait.",
			Emotion = "Neutral",
			SoundId = "rbxassetid://77047166293649"
		},
		ThisNotPartOfTheTest = {
			Subtitle = "WWWWHHHHAAATTTTT IIIIISSSSS HHHAPPIINNG!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! GRAB ON TO SOMETHING!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
			Emotion = "Shocked",
			SoundId = "rbxassetid://71689573443030"
		},
		whatdoido = {
			Subtitle = "WHATDOIDOWHATDOIDOWHATWDOWIHJWEIJWDIUASHDUIBDOLIWUEGBFOLPIEWUBGFL",
			Emotion = "Shocked",
			SoundId = "rbxassetid://113029444786387"
		}
    }
}